sonar.projectKey=mfe-angular13
sonar.projectName=mfe-angular13
sonar.projectVersion=1.0

sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.typescript.tsconfigPath=tsconfig.app.json

sonar.exclusions=dist/**,node_modules/**,trivy/**
